import { defineConfig } from 'oxfmt'

export default defineConfig({
  $schema: './node_modules/oxlint/configuration_schema.json',
  plugins: [
    'eslint',
    'import',
    'jsdoc',
    'oxc',
    'react',
    'react-perf',
    'typescript',
    'unicorn',
    'vitest',
  ],
  jsPlugins: ['oxlint-tailwindcss'],
  categories: {
    correctness: 'warn',
  },
  rules: {
    'no-unused-vars': 'error',
    'eslint/no-unused-vars': 'error',
    'react/no-children-prop': 'error',
    'tailwindcss/no-unknown-classes': 'error',
    'tailwindcss/no-duplicate-classes': 'error',
    'tailwindcss/no-conflicting-classes': 'error',
    'tailwindcss/no-deprecated-classes': 'error',
    'tailwindcss/no-unnecessary-whitespace': 'error',
    'tailwindcss/no-dark-without-light': 'warn',
    'tailwindcss/no-contradicting-variants': 'warn',
    'tailwindcss/enforce-canonical': 'warn',
    'tailwindcss/enforce-sort-order': 'warn',
    'tailwindcss/enforce-shorthand': 'warn',
    'tailwindcss/enforce-logical': 'off',
    'tailwindcss/enforce-physical': 'off',
    'tailwindcss/enforce-consistent-important-position': 'warn',
    'tailwindcss/enforce-negative-arbitrary-values': 'warn',
    'tailwindcss/enforce-consistent-variable-syntax': 'warn',
    'tailwindcss/consistent-variant-order': 'warn',
    'tailwindcss/max-class-count': 'off',
    'tailwindcss/enforce-consistent-line-wrapping': 'off',
    'tailwindcss/no-restricted-classes': 'off',
    'tailwindcss/no-arbitrary-value': 'off',
    'tailwindcss/no-hardcoded-colors': 'warn',
    'tailwindcss/no-unnecessary-arbitrary-value': 'warn',
  },
  settings: {
    'jsx-a11y': {
      polymorphicPropName: null,
      components: {},
      attributes: {},
    },
    tailwindcss: {
      entryPoint: './app/src/styles/input.css',
    },
    next: {
      rootDir: [],
    },
    react: {
      formComponents: [],
      linkComponents: [],
      version: null,
      componentWrapperFunctions: [],
    },
    jsdoc: {
      ignorePrivate: false,
      ignoreInternal: false,
      ignoreReplacesDocs: true,
      overrideReplacesDocs: true,
      augmentsExtendsReplacesDocs: false,
      implementsReplacesDocs: false,
      exemptDestructuredRootsFromChecks: false,
      tagNamePreference: {},
    },
    vitest: {
      typecheck: false,
    },
  },
  env: {
    builtin: true,
  },
  globals: {},
  options: {
    typeAware: true,
  },
  ignorePatterns: [],
})
